#' Parameters for calculating the SDIs. Provided by the ScientSDI function.
#'
#' Contains parameters of the gamma and GEV distributions and the Pr(Rain=0).
#'
#' @format A 13-column matrix with 48 rows
#'
#' \describe{
#' \item{lon}{longitude in decinal degrees}
#' \item{lat}{latitude in decinal degrees}
#' \item{quart.month}{The quartile of each month}
#' \item{alfa.rain}{Shape parameter of the gamma distribution}
#' \item{beta.rain}{Scale parameter of the gamma distribution}
#' \item{probzero.rain}{Probability of rain=0}
#' \item{loc.harg}{Location parameter of the GEV distribution, EP calculated by HS method}
#' \item{sc.harg}{Scale parameter of the GEV distribution, EP calculated by HS method}
#' \item{sh.harg}{Shape parameter of the GEV distribution, EP calculated by HS method}
#' \item{loc.pm}{Location parameter of the GEV distribution, EP calculated by PM method}
#' \item{sc.pm}{Scale parameter of the GEV distribution, EP calculated by PM method}
#' \item{sh.pm}{Shape parameter of the GEV distribution, EP calculated by PM method}
#' \item{TS}{Time scale at which the SDIs will be calculated}
#' }
#'
#' @source {Generated by the ScientSDI.R function using NASAPOWER data}
#'
#' @examples
#' data(DistPar)
"DistPar"
