#' Example Data of the Input Required by the Accuracy Function
#'
#' Contains pairs of reference and estimated data.
#'
#' @format A \code{data.frame} with 2 variables and 1434 rows.
#'
#' \describe{
#' \item{PE_obs}{PE data from a reference weather station}
#' \item{PE_est}{PE data from the \acronym{NASA} \acronym{POWER} project}
#' }
#'
#' @source Generated by the PowerSDI package using data from \acronym{NASA}
#'   \acronym{POWER} and Agronomic Institute.
#'
#' @examples
#' data(ObsEst)
"ObsEst"
