#' Example of the input required by the Accuracy function.
#'
#' Contains pairs of reference and estimated data.
#'
#' @format A 2-column matrix with 1434 rows
#'
#' \describe{
#' \item{PE_obs}{PE data from a reference weather station}
#' \item{PE_est}{PE data from the NASAPOWER project}
#' }
#'
#' @source {Generated by the PowerSDI package using data from NASAPOWER and Agronomic Institute}
#'
#' @examples
#' data(ObsEst)
"ObsEst"
